### ISSUE TITLE
With the new version of Appium, when running tests, an error The desired should not include both of an 'appPackage' and a 'browserName'

### ISSUE THREAD

**Issue by Nikonovaa** [appium/appium#12300]
## The problem

With the new version of Appium, when running tests, an error The desired should not include both of an 'appPackage' and a 'browserName'

## Environment

Appium version: 1.11.1
Desktop OS/version used to run Appium: Windows
Mobile platform/version under test: Android 8.0.0
Real device or emulator/simulator: real
Appium CLI or Appium.app|exe: Appium.exe

## Details

I use Appium + Behat + Mink. 
I never pass 'browserName'. I try to
comment out and to change capability 'browserName' in Selenium2Driver and AndoidFactory and everything where I found this capability . 
Then I try use "browserName": "" and "browserName": null. 
But it wasn't help. 

## Link to Appium logs
```

[Appium] Welcome to Appium v1.11.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"browserName":"remote","name":"Behat feature suite","tags":["DESKTOP-P63NJAU","PHP 5.6.30"],"autoWebview":true,"appPackage":"androidd.arnica.network1","appActivity":"androidd.arnica.network1.MainActivity","platformName":"Android","platformVersion":"8.0.0","deviceName":"Galaxy J8","browser":"firefox","marionette":null,"ignoreZoomSetting":false,"automationName":"Appium"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"remote","name":"Behat feature suite","tags":["DESKTOP-P63NJAU","PHP 5.6.30"],"autoWebview":true,"appPackage":"androidd.arnica.network1","appActivity":"androidd.arnica.network1.MainActivity","platformName":"Android","platformVersion":"8.0.0","deviceName":"Galaxy J8","browser":"firefox","marionette":null,"ignoreZoomSetting":false,"automationName":"Appium"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1552548158801 (12:22:38 GMT+0500 (RTZ 4 (зима)))
[Appium] DeprecationWarning: 'automationName' capability was not provided. Future versions of Appium will require 'automationName' capability to be set for Android sessions.
[Appium] Setting automation to 'UiAutomator1'. 
[Appium] Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator1 framework is not maintained anymore by the OS vendor.
[Appium] Creating new AndroidDriver (v4.8.0) session
[Appium] Capabilities:
[Appium]   browserName: remote
[Appium]   name: Behat feature suite
[Appium]   tags: {
[Appium]     0: DESKTOP-P63NJAU
[Appium]     1: PHP 5.6.30
[Appium]   }
[Appium]   autoWebview: true
[Appium]   appPackage: androidd.arnica.network1
[Appium]   appActivity: androidd.arnica.network1.MainActivity
[Appium]   platformName: Android
[Appium]   platformVersion: 8.0.0
[Appium]   deviceName: Galaxy J8
[Appium]   browser: firefox
[Appium]   marionette: null
[Appium]   ignoreZoomSetting: false
[Appium]   automationName: Appium
[BaseDriver] Creating session with MJSONWP desired capabilities: {"browserName":"remote","na...
[BaseDriver] The following capabilities were provided, but are not recognized by appium: name, tags, browser, marionette, ignoreZoomSetting.
[AndroidDriver] Error: The desired should not include both of an 'appPackage' and a 'browserName'
[AndroidDriver]     at Object.wrappedLogger.errorAndThrow (C:\Users\Nikonova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:78:13)
[AndroidDriver]     at Object.errorAndThrow [as validateDesiredCaps] (C:\Users\Nikonova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\android-helpers.js:720:14)
[AndroidDriver]     at AndroidDriver.validateDesiredCaps (C:\Users\Nikonova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:488:20)
[AndroidDriver]     at AndroidDriver.validateDesiredCaps [as createSession] (C:\Users\Nikonova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\session.js:45:8)
[AndroidDriver]     at AndroidDriver.createSession (C:\Users\Nikonova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\driver.js:61:43)
[AndroidDriver]     at AppiumDriver.createSession (C:\Users\Nikonova\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\lib\appium.js:310:43)
[AndroidDriver]     at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Code To Reproduce Issue [ Good To Have ]

My behat.yml:

```
application:
  extensions:
    Behat\MinkExtension:
      javascript_session:  'selenium2'
      sessions:
        selenium2:
          appium:
            capabilities: {"autoWebview": true, "appPackage": "androidd.arnica.network1", "appActivity": "androidd.arnica.network1.MainActivity", "platformName": "Android", "platformVersion": "8.0.0", "deviceName": "Galaxy J8"}
```

**Comment by saikrishna321** [comment]
Pls remove browserName from capabilities

**Comment by Nikonovaa** [comment]
@saikrishna321 there is no browserName in capabilities

```
application:
  extensions:
    Behat\MinkExtension:
      javascript_session:  'selenium2'
      sessions:
        selenium2:
          appium:
            capabilities: {"autoWebview": true, "appPackage": "androidd.arnica.network1", "appActivity": "androidd.arnica.network1.MainActivity", "platformName": "Android", "platformVersion": "8.0.0", "deviceName": "Galaxy J8"}
```
