### ISSUE TITLE
(v2) appium install driver deletes previous installed driver(s) when installing multiple drivers.

### ISSUE THREAD

**Issue by cmaganu** [appium/appium#16674]
## The problem

I installed appium 2.0.0-beta.27 via npm, 
first installed uiautomator2 driver - run test with uiautomator2 -> all ok
then installed espresso driver - run test with uiautomator2 again -> error:
```
Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UIAutomator2' and platformName android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Cannot find module '/home/cmaganu/.appium/node_modules/appium-uiautomator2-driver
```

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.27
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: Ubunntu 20.10
* Node.js version (unless using Appium.app|exe): v16.14.2
* Npm or Yarn package manager: npm 8.5.5
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: cli

## Details
- after `appium driver install uiautomator2`:
```
cmaganu@cma-x1:~/git/lt-appium-mobile-tests(main)$ ls -Al ~/.appium/node_modules/
total 128
drwxrwxr-x 5 cmaganu cmaganu   4096 mar 28 16:45 appium-uiautomator2-driver
drwxrwxr-x 3 cmaganu cmaganu   4096 mar 28 16:45 .cache
-rw-rw-r-- 1 cmaganu cmaganu 121877 mar 28 16:45 .package-lock.json
```
```
cmaganu@cma-x1:~/git/lt-appium-mobile-tests(main)$ cat  ~/.appium/node_modules/.cache/appium/extensions.yaml 
drivers:
  uiautomator2:
    automationName: UiAutomator2
    platformNames:
      - Android
    mainClass: AndroidUiautomator2Driver
    pkgName: appium-uiautomator2-driver
    version: 2.0.5
    installType: npm
    installSpec: uiautomator2
plugins: {}
schemaRev: 2
```
```
cmaganu@cma-x1:~/git/lt-appium-mobile-tests(main)$ appium driver list --installed
✔ Listing installed drivers
- uiautomator2@2.0.5 [installed (NPM)]
```
- after `appium driver install espresso`:
```
cmaganu@cma-x1:~/git/lt-appium-mobile-tests(main)$ appium driver list --installed
✔ Listing installed drivers
- uiautomator2@2.0.5 [installed (NPM)]
- espresso@2.2.0 [installed (NPM)]
```
```
cmaganu@cma-x1:~/git/lt-appium-mobile-tests(main)$ ls -Al ~/.appium/node_modules/
total 708
drwxrwxr-x 6 cmaganu cmaganu   4096 mar 28 16:49 appium-espresso-driver
drwxrwxr-x 3 cmaganu cmaganu   4096 mar 28 16:45 .cache
-rw-rw-r-- 1 cmaganu cmaganu 714864 mar 28 16:49 .package-lock.json
```
```
cmaganu@cma-x1:~/git/lt-appium-mobile-tests(main)$ cat  ~/.appium/node_modules/.cache/appium/extensions.yaml 
drivers:
  uiautomator2:
    automationName: UiAutomator2
    platformNames:
      - Android
    mainClass: AndroidUiautomator2Driver
    pkgName: appium-uiautomator2-driver
    version: 2.0.5
    installType: npm
    installSpec: uiautomator2
  espresso:
    automationName: Espresso
    platformNames:
      - Android
    mainClass: EspressoDriver
    pkgName: appium-espresso-driver
    version: 2.2.0
    installType: npm
    installSpec: espresso
plugins: {}
schemaRev: 2
```
`.appium/package.json` is empty
