### ISSUE TITLE
iOS tests are suddenly failing:  Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Unable to start WebDriverAgent

### ISSUE THREAD

**Issue by tking16** [appium/appium#19529]
I'm in the process of changing our test suite from sequential running to parallel. Without making any changes that I remember from yesterday the same commands to run the test suite are now failing. Running them in the original sequential way still seems fine but not sure how or why things are failing now all of a sudden.

One of my Appium yaml files:
```yaml
server:
  port: 4733
  use-drivers:
    - xcuitest
  default-capabilities:
    appium:wdaLocalPort: 8101
    appium:derivedDataPath: ${DERIVED_DATA_PATH}
    appium:showXcodeLog: true
```

* xcuitest version: 4.35.0 
* Using Selenium Grid version: 4.16.1

[Full Appium Logs](https://github.com/appium/appium/files/13675247/appium2.log)
