### ISSUE TITLE
Question: Unable to connect to WDA on GitHub Actions macos

### ISSUE THREAD

**Issue by unickq** [appium/appium#20601]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi there,

I'm trying to launch appium test on Github Action macos with iOS simulator. Appium wrapped with latest WDIO
Always receiving 
```2024-09-23 10:53:24:060 [29de9184][XCUITestDriver@2ae8] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2024-09-23 10:53:24:067 uncaughtException: write EPIPE
Error: write EPIPE
```
no matter what timeouts, configs, emulators, os versions I use

### Expected Behavior

I expected it to work somehow but couldn't find a working example yet.

### Appium launch params
```js
      "appium",
      {
        args: {
          address: "127.0.0.1",
          localTimezone: true,
          allowCors: true,
          relaxedSecurity: true,
          logTimestamp: true,
          log: "./logs/appium-ios.log",
        },
      },
```

### Caps

```js
  capabilities: [
    {
      browserName: "safari",
      platformName: "iOS",
      "wdio:maxInstances": 1,
      "appium:deviceName": process.env.ios_model || "iPhone 14",
      "appium:platformVersion": process.env.ios_version || "17.5",
      "appium:orientation": "PORTRAIT",
      "appium:automationName": "XCUITest",
      "appium:newCommandTimeout": 240,
      // "appium:showXcodeLog": false,
      // "appium:showIOSLog": false,
      // "appium:launchWithIDB": true,
      // "appium:wdaLocalPort": 8101,
      "appium:wdaLaunchTimeout": 60_000 * 5,
      "appium:wdaStartupRetries": 5,
      "appium:wdaStartupRetryInterval": 30_000,
      "appium:wdaConnectionTimeout": 60_000 * 3,
      "appium:simulatorStartupTimeout": 60_000 * 3,
    },
  ],
```

### Actions code
```yml
jobs:
  iOS-browser:
    runs-on: macos-latest
    timeout-minutes: 10
    # https://github.com/futureware-tech/simulator-action/wiki/Devices-macos-14
    env:
      ios_model: "iPhone 14"
      ios_version: "17.5"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: 🧩 Install Dependencies
        run: npm ci
      - name: Start iOS Device
        uses: futureware-tech/simulator-action@v3
        with:
          model: ${{ env.ios_model }}
          os_version: ${{ env.ios_version }}
      - name: Run tests iOS emulator
        run: |
          npx appium driver doctor xcuitest
          npm run ios.browser
```

### Environment

- Operating system: macos of github actions
- Appium server version (output of `appium --version`): 2.11.4
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2@3.8.0
- Appium plugin(s) and their version(s) (`appium plugin list`): none
- Node.js version (output of `node --version`): 20.17.0
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: GitHub action - macos-latest
- Real device or emulator/simulator: any simulator

### Link to Appium Logs

https://gist.github.com/unickq/c30a0d81a0d1c0db78fe1523b6a22141

### Further Information

Emulators launched with https://github.com/futureware-tech/simulator-action

**Comment by mykola-mokhnach** [comment]
I was observing similar error reports when an output stream gets unexpectedly closed by the OS, for example a terminal where the server process has been executed. I assume this is happening because of various timeouts, both client and server.

> 2024-09-23 10:53:22:539 [HTTP] <-- POST /session - - ms - - 

This log line, for example means the client has stopped waiting for session creation request unexpectedly. 

To workaround this make sure you allow enough time for the client and the server to build WDA sources. It might be also a good idea to prebuild WDA before starting a session. Check the [java-client](https://github.com/appium/java-client/blob/9b3194e29857b6204f51d7f198d3583d2d904e50/.github/workflows/gradle.yml#L140) pipeline, for example.

**Comment by unickq** [comment]
@mykola-mokhnach 

Tried 
```yml
      - name: 📱 Start iOS Device
        uses: futureware-tech/simulator-action@v3
        with:
          model: ${{ env.ios_model }}
          os_version: ${{ env.ios_version }}
      - name: Prebuild
        run: |
          npx appium driver doctor xcuitest
          npx appium driver run xcuitest build-wda
      - name: 🧪 Run tests iOS emulator
        run: |
          npm run ios.browser
```

![image](https://github.com/user-attachments/assets/a971a506-9658-4088-8d3b-e4b7da2e7885)
https://gist.github.com/unickq/f0d5526941c8620f3d7984bb5058000c

Got the same error. Selecting the same xcode to 15.4 as java client has - did nothing :(

**Comment by unickq** [comment]
I created a repo for it - https://github.com/unickq/appium-debug-20601; actions logs included

**Comment by mykola-mokhnach** [comment]
i don't observe any actual server issues in the failed log. The client keeps disconnecting from it before the session creation completes. Maybe you should just start appium server separately instead of relying on wdio?

**Comment by unickq** [comment]
Mentioned it in previous comment - I'm launching
```js
const { remote } = require("webdriverio");

const wdOpts = {
  hostname: "localhost",
  port: 4723,
  logLevel: "info",
  capabilities: {
    platformName: "iOS",
    "appium:automationName": "XCUITest",
    "appium:browserName": "Safari",
    "appium:deviceName": process.env.ios_model || "iPhone 15",
    "appium:platformVersion": process.env.ios_version || "17.2",
  },
};

async function runTest() {
  const driver = await remote(wdOpts);
  await driver.navigateTo("https://www.google.com");
  console.log(await driver.getTitle());
}

runTest().catch(console.error);
```

with

```yml
      - name: 🧪 Run Appium
        run: |
          npx appium --log-timestamp --log ./logs/appium-ios.log --log-level debug &
      - name: 🧪 Run tests iOS emulator
        run: |
          node x.cjs
```

fails with `Failed to create session`, but passes locally as original code

https://github.com/unickq/appium-debug-20601/actions/runs/10995142575/job/30525257047

**Comment by KazuCocoa** [comment]
Perhaps you set `connectionRetryTimeout` as 2 mins. It means the wdio client stop the http request after 120 seconds. It is probably the reason.
https://github.com/unickq/appium-debug-20601/blob/main/configs/wdio.ios.browser.conf.ts

**Comment by unickq** [comment]
@KazuCocoa , what do you mean?
wdio has 120s with three attempts. 

```bash
2024-09-23 11:58:12:073 [acf677a9][XCUITestDriver@f638] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2024-09-23 11:58:12:166 [acf677a9][XCUITestDriver@f638] connect ECONNREFUSED 127.0.0.1:8100
....
2024-09-23 11:59:19:041 [acf677a9][XCUITestDriver@f638] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
2024-09-23 11:59:19:049 uncaughtException: write EPIPE
Error: write EPIPE
```

But WDA fails in one minute. Even with any of these 
```js
      // "appium:wdaLaunchTimeout": 60_000 * 5,
      // "appium:wdaStartupRetries": 5,
      // "appium:wdaStartupRetryInterval": 30_000,
      // "appium:wdaConnectionTimeout": 60_000 * 3,
      // "appium:simulatorStartupTimeout": 60_000 * 3,
```

There's https://github.com/appium/appium/issues/20601#issuecomment-2368527979 from https://appium.io/docs/en/2.0/quickstart/test-js/, has the same error

**Comment by KazuCocoa** [comment]
The connection error indicated that WDA hadn't started yet. Probably xcodebuild took longer time that your appium client's connectionRetryTimeout, so the client ended the HTTP connection.

For example, https://gist.github.com/unickq/f0d5526941c8620f3d7984bb5058000c logs had:

```
2024-09-23 11:58:07:553 [acf677a9][XCUITestDriver@f638] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/runner/work/ui-mobile-tests/ui-mobile-tests/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/runner/Library/Developer/Xcode/DerivedData/WebDriverAgent-bjkfltjzywmfwagcceicbvdqouyw -destination id=F9EFD965-9E4A-46BA-926F-C8575C0E7EA6 IPHONEOS_DEPLOYMENT_TARGET=17.5 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Users/runner/work/ui-mobile-tests/ui-mobile-tests/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
2024-09-23 11:58:07:558 [acf677a9][XCUITestDriver@f638] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
2024-09-23 11:58:12:049 [acf677a9][XCUITestDriver@f638] Waiting up to 300000ms for WebDriverAgent to start
```

Then, appium keeps waiting for WDA to be started up to `Waiting up to 300000ms for WebDriverAgent to start`. Then, the `/status` request continues. Aa previous mykola's comment, probably your appium client ended the HTTP connection before getting the response as less than `Waiting up to 300000ms for WebDriverAgent to start`.

Have you increased the connectionRetryTimeout over `300000ms` for example?

> But WDA fails in one minute. Even with any of these

Did you check how long xcodebuild such as `xcodebuild build-for-testing test-without-building -project /Users/runner/work/ui-mobile-tests/ui-mobile-tests/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/runner/Library/Developer/Xcode/DerivedData/WebDriverAgent-bjkfltjzywmfwagcceicbvdqouyw -destination id=F9EFD965-9E4A-46BA-926F-C8575C0E7EA6 IPHONEOS_DEPLOYMENT_TARGET=17.5 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Users/runner/work/ui-mobile-tests/ui-mobile-tests/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent` in the log took to complete on the GHA env?


https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/helpers/session.js
https://github.com/appium/appium-xcuitest-driver/blob/master/test/functional/desired.js

these are our example code running on GHA. They need much longer timeout config to complete the xcodebuild.

**Comment by unickq** [comment]
@KazuCocoa thanks for your ideas.
Yes, I tried prebuild appium as @mykola-mokhnach suggested from java repo. PR for that - https://github.com/unickq/appium-debug-20601/pull/1

```bash
npx appium driver run xcuitest build-wda
```

for this config:
```js
export const config: WebdriverIO.Config = {
  ...baseConfig,
  specs: ["../tests/browser/**/*.ts"],
  connectionRetryTimeout: 60_000 * 5,
  connectionRetryCount: 3,
  maxInstances: 1,
  capabilities: [
    {
      browserName: "safari",
      platformName: "iOS",
      "appium:deviceName": process.env.ios_model || "iPhone 15",
      "appium:platformVersion": process.env.ios_version || "17.2",
      "appium:orientation": "PORTRAIT",
      "appium:automationName": "XCUITest",
      "appium:newCommandTimeout": 240,
      "appium:showXcodeLog": true,
      // "appium:showIOSLog": false,
      // "appium:launchWithIDB": true,
      "appium:wdaLaunchTimeout": 60_000 * 5,
      "appium:wdaStartupRetries": 5,
      "appium:wdaStartupRetryInterval": 30_000,
      "appium:wdaConnectionTimeout": 60_000 * 5,
      // "appium:simulatorStartupTimeout": 60_000 * 3,
    },
  ],
};
```

```yml
      - name: 📱 Start iOS Device
        uses: futureware-tech/simulator-action@v3
        with:
          model: ${{ env.ios_model }}
          os_version: ${{ env.ios_version }}
      - name: 🔧 Prebuild Appium
        run: |
          # npm install --location=global appium
          # appium driver list --installed
          # appium driver install xcuitest
          # npx appium driver doctor xcuitest
          npx appium driver run xcuitest build-wda
      - name: 🧪 Run tests iOS emulator
        run: |
          npm run ios.browser
```

From what I see for the build it took ~3 min - https://github.com/unickq/appium-debug-20601/actions/runs/11010291818/job/30571874579, but probably it boot up different emulator.
