### ISSUE TITLE
Feature Request: Basic appium android docker image to kickstart env conf

### ISSUE THREAD

**Issue by F2X** [appium/appium#6979]
## The problem

I need to test appium integration inside an existing selenium-hub environment, using a simple docker-compose. For now, I have to manually install appium on a hardware, and configure it to plug it with the selenium hub.
It will be a good idea to create a Docker image that contains Appium with minimal features to allow infrastructure debugging. E.g. a docker image based on debian, with the Android SDK and a preconfigured simulator conf, which have default conf just to test the dialog between an Appium node and a selenium hub.

```
hub:
  image: selenium/hub
  ports:
    - 4444:4444

node-chrome:
  image: selenium/node-chrome
  links:
    - hub

node-firefox:
  image: selenium/node-firefox
  links:
    - hub

node-appium-android:
  image: appium/node-appium-android
  links:
    - hub
```
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: Debian stretch
- Node.js version (unless using Appium.app|exe): 6
- Mobile platform/version under test: Android
- Real device or emulator/simulator: N/A
- Appium CLI or Appium.app|exe: N/A
## Details

See above
## Link to Appium logs

N/A
## Code To Reproduce Issue [ Good To Have ]

N/A
