### ISSUE TITLE
Feature request for Android driver: promote remoteAdbHost option

### ISSUE THREAD

**Issue by serggl** [appium/appium#8564]
From the `appium-adb` code I see that there is an option called `remoteAdbHost` ([lib/adb.js](https://github.com/appium/appium-adb/blob/fb52f6fe12a2f1a8e0e96d631ffdfe5ef403151c/lib/adb.js#L41)) but it is not currently promoted in base driver ([lib/desired-caps.js](https://github.com/appium/appium-android-driver/blob/b9f6a9501c6d0cbc8b7919f4aebb89e21aa0a9f6/lib/desired-caps.js)). Same time `adbPort` option is available... 

`remoteAdbHost` option could be very helpfull in docker environment where emulator could be running in a container separate from the appium server (Which is what I currently trying to setup), but  appium now is filtering out this option.
And `adb tcpip / adb connect` with a `deviceName` capability  trick does not really works for an emulator running an a docker container.

Is there a specific reason why appium has a ADB's port option configurable but not the host? If no, can we make it available?

Thank you.

**Comment by dpgraham** [comment]
@serggl This is a good idea. The use-case you described is probably a fairly common one. 

I'll add this to our triaged pipeline. Not certain when we'll get to it, but we do accept PR's.

**Comment by serggl** [comment]
Here is the PR (https://github.com/appium/appium-android-driver/pull/241), relatively simple.
However I've found that just having this option set is not enough to make appium communicate to the emulator betweeen the docker containers.
The problem is in `AppiumBootstrap` app. It still needs an appium container's port 4724 (bootstrap port) to be forwarded to the emulator container. Solved that with the `iptables` setup.

Here's my compose file for the once who interested:
```yaml
version: "2"

services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome

  emulator:
    container_name: emulator
    image: jenkins-appium-emulator
    command: ./run_emulator.sh

  appium:
    container_name: appium
    image: jenkins-appium-emulator
    privileged: true
    command: ./run_appium.sh

  fuse-box:
    container_name: fuse-box
    image: ...# image running my specs
```
`run_appium.sh` script:
```bash
iptables -t nat -A OUTPUT -m addrtype --src-type LOCAL --dst-type LOCAL -p tcp --dport 4700 -j DNAT --to-destination $(getent hosts emulator | awk '{ print $1 }')
iptables -t nat -A POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE
sysctl -w net.ipv4.conf.all.route_localnet=1
echo "net.ipv4.conf.all.route_localnet=1" >> /etc/sysctl.conf
appium --bootstrap-port 4700
```
`run_emulator.sh` script:
```bash
adb -a nodaemon server &
emulator64-arm -avd Nexus -no-boot-anim -no-window -noaudio -gpu off -memory 1024 -skin 1080x1920
```
caps file for the ruby library:
```
[caps]
platformName = 'Android'
deviceName = 'Android Emulator'
appPackage = '...'
appActivity = '...'
remoteAdbHost = 'emulator'

[appium_lib] 
server_url = "http://appium:4723/wd/hub"
```
